#!/usr/bin/env bash
# Stamp a generated Godot script with the app marketing version and build number.
#
# Explicit version (`make ios 1.2.3`) mirrors tools/set_ios_version.sh: both the
# marketing version and build number become the passed value. Bare local exports
# use export_presets.cfg; Xcode Cloud bare exports use CI_BUILD_NUMBER as the
# monotonic build number.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:?usage: stamp_build_info.sh <out.gd> [version]}"
VERSION="${2:-}"

if [ -n "$VERSION" ] && ! [[ "$VERSION" =~ ^[0-9]+(\.[0-9]+){0,2}$ ]]; then
	echo "stamp_build_info: '$VERSION' is not a valid version (expected N, N.N, or N.N.N)" >&2
	exit 1
fi

preset_value() {
	local key="$1"
	awk -F= -v key="$key" '
		$1 == key {
			value = $2
			gsub(/^"/, "", value)
			gsub(/"$/, "", value)
			print value
			exit
		}
	' "$ROOT/export_presets.cfg"
}

MARKETING="${VERSION:-$(preset_value "application/short_version")}"
BUILD="${VERSION:-${CI_BUILD_NUMBER:-$(preset_value "application/version")}}"

if ! [[ "$MARKETING" =~ ^[0-9]+(\.[0-9]+){0,2}$ ]]; then
	echo "stamp_build_info: marketing version '$MARKETING' is not valid" >&2
	exit 1
fi
if ! [[ "$BUILD" =~ ^[0-9]+(\.[0-9]+){0,2}$ ]]; then
	echo "stamp_build_info: build number '$BUILD' is not valid" >&2
	exit 1
fi

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<GDSCRIPT
extends RefCounted
# Generated by tools/stamp_build_info.sh; do not edit.

const MARKETING_VERSION := "$MARKETING"
const BUILD_NUMBER := "$BUILD"

static func info() -> Dictionary:
	return {"marketing_version": MARKETING_VERSION, "build_number": BUILD_NUMBER}
GDSCRIPT

echo "stamp_build_info: version $MARKETING (build $BUILD) -> $OUT"
